# Generated by Django 3.2.6 on 2023-03-31 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_completed',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('desc', models.TextField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', '#00FF00'), ('moderate', '#FFFF00'), ('high', '#ED4726')], max_length=1000)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_tasks', to='main.todo')),
            ],
        ),
    ]
