# Generated by Django 3.2.6 on 2023-03-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230401_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='todo',
        ),
    ]
