# Generated by Django 3.2.6 on 2023-03-31 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230401_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_date', to='main.todo', to_field='published'),
        ),
    ]
