# Generated by Django 3.2.6 on 2023-03-31 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230401_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='color',
        ),
    ]
