# Generated by Django 3.2.6 on 2023-03-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_priority_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#00FF00', '#00FF00'), ('#FFFF00', '#FFFF00'), ('#ED4726', '#ED4726')], max_length=1000),
        ),
    ]
