# Generated by Django 3.2.6 on 2023-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='isOverdue',
            field=models.BooleanField(default=False),
        ),
    ]
