# Generated by Django 3.2.6 on 2023-04-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230409_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#64fa64', '#64fa64'), ('#FFFF00', '#FFFF00'), ('#ED4726', '#ED4726')], max_length=1000),
        ),
    ]
