# Generated by Django 3.2.6 on 2023-04-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#c8fac8', '#c8fac8'), ('#FFFF00', '#FFFF00'), ('#ED4726', '#ED4726')], max_length=1000),
        ),
    ]
