# Generated by Django 3.2.6 on 2023-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#c8fac8', '#c8fac8'), ('#fafaa7', '#fafaa7'), ('#ff9082', '#ff9082')], max_length=1000),
        ),
    ]
