# Generated by Django 3.2.6 on 2023-04-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#c8fac8', 2), ('#fafaa7', 1), ('#ff9082', 0)], max_length=1000),
        ),
    ]
