name: backend-Todo
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: logging pwd
      run: pwd
    - name: logging directory list
      run: ls -l
    - name: Todo Test Cases
      run: python manage.py test | cd backend
    - name: logging test
      run: echo "Test Logging Succeeded"
   

